name: taac2026-torch
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.11.0+cu128
      - torchvision==0.26.0+cu128
      - torchaudio==2.11.0+cu128
      - --index-url https://download.pytorch.org/whl/cu128
      - pandas
      - pyarrow
      - numpy
      - scikit-learn
      - pyyaml
      - tqdm
      - tensorboard
